version: "3"
services:
  sketch2face:
    build: .
    image: nthacks/sketch2face
    container_name: sketch2face
    restart: unless-stopped
    volumes:
      # - ~/workspace/input:/workspace/input
      - ./output:/workspace/output
      # - C:\Users\nisch\Desktop\project\sketch2face\input:/workspace/input
      # - C:\Users\nisch\Desktop\project\sketch2face\output:/workspace/output
      # - C:\Users\nisch\Desktop\project\sketch2face\app:/workspace/app
#    ports:
#      - 8080:8080
  nginx:
    restart: unless-stopped
    build: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot-etc/:/etc/letsencrypt/
      - ./certbot-var:/var/lib/letsencrypt
    environment:
      - CERTBOT_EMAIL=nischal@nthacks.com
